version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: runit-postgres
    restart: always
    environment:
      POSTGRES_USER: runit_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: runit
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
